name: unpub
description: Self-hosted private Dart Pub server for Enterprise, with a simple web interface to search and view packages information.
version: 1.2.1
homepage: https://github.com/bytedance/unpub
author: Rongjian Zhang <pd4d10@gmail.com>

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  args: ^1.5.1
  shelf: ^0.7.5
  shelf_router: ^0.7.0
  http_parser: ^3.1.3
  http: ^0.12.0
  archive: ^2.0.8
  logging: ^0.11.3
  meta: ^1.1.7
  googleapis: ^0.54.0
  yaml: ^2.1.15
  pub_semver: ^1.4.2
  json_annotation: ^3.0.0
  mongo_dart: ^0.3.6
  mime: ^0.9.6+3
  intl: ^0.16.0
  path: ^1.6.2

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.6.1
  build_runner: ^1.0.0
  json_serializable: ^3.2.3
  shelf_router_generator: ^0.7.1
  collection: ^1.14.11
  dart_style: ^1.2.7

executables:
  unpub: unpub
